language: ruby

rvm:
 - 2.2.3

# Adapted from https://github.com/iblancasa/blog_files/blob/master/.travis.yml
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git sshpass
  - |
    gem install bundler
    bundle install
    git config --global user.email "dgiimblog@gmail.com"
    git config --global user.name "dgiimbot"
    echo ${KNOWN_HOST_RSA} >> ~/.ssh/known_hosts
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && sshpass -p ${TUX_SSHPASS} git clone -b master ${TUX_SSH_REPO} _site # && rm -rf _site/*
    cat _config.yml _tux.yml

script: deploy.sh

after_script:
  - cd _site/
  - |
    cat index.html
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && (git ls-files --deleted -z | xargs -0 git rm) && \
    git add * && \
    git add . && \
    git commit -m "`date`" && \
    sshpass -p ${TUX_SSHPASS} git push origin master --quiet

branches:
  only:
    - gh-pages
