language: ruby

rvm:
 - 2.2.3

git:
  submodules: false

# Adapted from https://github.com/iblancasa/blog_files/blob/master/.travis.yml
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install -y git sshpass
  - |
    gem install bundler
    git config --global user.email "dgiimblog@gmail.com"
    git config --global user.name "dgiimbot"
    echo ${KNOWN_HOST_RSA} >> ~/.ssh/known_hosts
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && sshpass -p ${TUX_SSHPASS} git clone -b master ${TUX_SSH_REPO} _site # && rm -rf _site/*
    chmod u+x deploy.sh

script: deploy.sh

after_script:
  - cd _site/
  - |
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && (git ls-files --deleted -z | xargs -0 git rm) && \
    git add * && \
    git add . && \
    git commit -m "`date`" && \
    sshpass -p ${TUX_SSHPASS} git push origin master --quiet
